php7:
    build: .
    dockerfile: Dockerfile
    volumes:
        - ./logs/apache:/var/log/apache2/
        - ${WWWFOLDER}:/var/www/html
        - ./config/apache2/vhosts/:/etc/apache2/sites-enabled/
    ports:
        - "80:80"
    links:
        - mysql

mysql:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=root
    volumes: 
        - ./config/mysql/mysql.cnf:/etc/mysql/mysql.conf.d/mysql.cnf
        - ./logs/mysql:/var/log/mysql/
        - ./etc/mysql:/docker-entrypoint-initdb.d
        - ./data:/var/lib/mysql