php7:
    build: .
    dockerfile: Dockerfile
    volumes:
        - ./logs/apache:/var/log/apache2/
        - ./logs/letsencrypt:/var/log/letsencrypt/
        - ${WWWFOLDER}:/var/www/html
        - ./config/apache2/vhosts/:/etc/apache2/sites-enabled/
    ports:
        - "80:80"
        - "443:443"
    links:
        - mysql

mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=root
    volumes: 
        - ./logs/mysql:/var/log/mysql/
        - ./etc/mysql:/docker-entrypoint-initdb.d
        - ./data:/var/lib/mysql
        - ./config/data/:/docker-entrypoint-initdb.d/
